### PR TITLE
Node as cluster

### PR DESCRIPTION
**Pull request by bkmeneguello**
I did a draft allowing normal nodes to be used as clusters, which is very draft yet and has some drawbacks.

### CODE REVIEW

**Comment by bkmeneguello** [comment]
Ok, I fixed the drawback, now it's possible to do:
```
from diagrams import Diagram
from diagrams.aws.network import VPC
from diagrams.aws.compute import EC2
from diagrams.aws.general import User

with Diagram("Sample Project"):
    with VPC("vpc-XXXXX"):
        with EC2("id-YYYYY") as i01:
            admin = User("admin")
        EC2("id-XXXXX") >> i01
```
sample_project

**Comment by gabriel-tessier** [comment]
@bkmeneguello 
Look really great!

About the example in the documentation what I understand is you want to show that we can write a cluster from the Cluster class or a Node to add the icon. But the problem is when you check the below render file is that it's render in the same cluster as the name is the same!
It render something like this:

mysql2

I rewrite the example from docs/guides/cluster.md hope it make more clear and we can see that it generate same cluster with same icon, i.e you 2 way to write the same thing:

```
from diagrams import Cluster, Diagram
from diagrams.aws.compute import ECS
from diagrams.aws.database import RDS, Aurora
from diagrams.aws.network import Route53, VPC


with Diagram("Simple Web Service with DB Cluster", show=False, filename="mysql"):
    dns = Route53("dns")
    web = ECS("service")

    with Cluster(label='VPC', icon=VPC):
        # using cluster with an icon
        with Cluster("DB ClusterA", icon=Aurora, icon_size=30):
            db_master1 = RDS("main")
            db_master1 - [RDS("replica1"), RDS("replica2")]
        # using the node
        with Aurora("DB ClusterB", cluster=True):
            db_master2 = RDS("main")
            db_master2 - [RDS("replica1"), RDS("replica2")]

        dns >> web >> db_master1
        dns >> web >> db_master2
```

mysql

I also rename to main replica!

I think that it's important to keep the Cluster as it to allow users to add icon, in a way that it will not brake old diagrams and make old one more easy to update if we want to add icon.
As you put in your comment in the other PR if "cluster=True" can be removed it will prevent complexity as there's already with before the node.

**Comment by bkmeneguello** [comment]
@gabriel-tessier 

Ok, fixed!

Also, the `cluster=True` is not needed anymore and I made possible to do Node/Cluster <-> Cluster edges (Only for Node as Cluster), notice the relation to the bottom Cluster.

```python
from diagrams import Cluster, Diagram
from diagrams.aws.compute import ECS
from diagrams.aws.database import RDS, Aurora
from diagrams.aws.network import Route53, VPC


with Diagram("Simple Web Service with DB Cluster", show=True, filename="mysql"):
    dns = Route53("dns")
    web = ECS("service")

    with Cluster(label='VPC', icon=VPC):
        # using cluster with an icon
        with Cluster("DB ClusterA", icon=ECS, icon_size=30):
            db_master1 = RDS("main")
            db_master1 - [RDS("replica1"), RDS("replica2")]
        # using the node
        with Aurora("DB ClusterA") as db2:
            db_master2 = RDS("main")
            db_master2 - [RDS("replica1"), RDS("replica2")]

        dns >> web >> db_master1
        dns >> web >> db2
```
mysql

**Comment by bkmeneguello** [comment]
I pushed one more feature to allow empty "Node as Cluster" to be rendered as a plain Node:
```
from diagrams import Cluster, Diagram
from diagrams.aws.compute import ECS
from diagrams.aws.database import RDS, Aurora
from diagrams.aws.network import Route53, VPC


with Diagram("Simple Web Service with DB Cluster", show=True, filename="mysql"):
    dns = Route53("dns")
    web = ECS("service")

    with Cluster(label='VPC', icon=VPC):
        # using cluster with an icon
        with Cluster("DB ClusterA", icon=ECS, icon_size=30):
            db_master1 = RDS("main")
            db_master1 - [RDS("replica1"), RDS("replica2")]
        # using the node
        with Aurora("DB ClusterA") as db2:
            pass

        dns >> web >> db_master1
        dns >> web >> db2
```
mysql

**Comment by bkmeneguello** [comment]
@gabriel-tessier @mingrammer @dan-ash 

Ok, I think I finished. I moved all common code to a `_Cluster` mixin, converted `Cluster` to be a `Node` subclass so all classes can behave equally. I think I didn't mess with the public API, so it should not trouble advanced users.
I'll change my PR to the official repo since it has changed a lot from the @dan-ash branch (but will keep his commits).

-- EDIT --
I can't change the repo, duh. @dan-ash could you please merge this PR (if you want) so we could follow the discussion at the main repo? If you don't want to merge, I'll create a new PR there.

**Review by dan-ash — APPROVED** [review]
Really Amazing job @bkmeneguello

**Pull request merged**
